export const ENV = {
  NODE_ENV: 'NODE_ENV',
  BOT_TOKEN: 'BOT_TOKEN',
  BOT_TEST_TOKEN: 'BOT_TEST_TOKEN',
  GUILD_ID: 'GUILD_ID',
  AFK_CHANNEL_ID: 'AFK_CHANNEL_ID',
  BILL_CHANNEL_ID: 'BILL_CHANNEL_ID',
  RAILWAY_ENVIRONMENT: 'RAILWAY_ENVIRONMENT',
  PORT: 'PORT',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  BILL_DB_NAME: 'BILL_DB_NAME',
  BILL_DB_USERNAME: 'BILL_DB_USERNAME',
  BILL_DB_PASSWORD: 'BILL_DB_PASSWORD',
} as const;
export type Env = (typeof ENV)[keyof typeof ENV];
